server {
    listen 80;
    server_name ai-learning.local;

    root "/Users/yangjing/www/ai-learning/public";

    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9002;

        fastcgi_index index.php;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED /var/www/html/public$fastcgi_path_info;

        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
